name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 22  # 设置 JDK 版本，这里是 17，你可以根据实际使用的 JDK 版本修改
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Run Maven build  # 新增的任务，用于执行 Maven 构建
      run: mvn clean test  # 执行 mvn clean test 命令来运行测试

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 22  # 设置 JDK 版本
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
      
    # This section is optional and depends on whether you need to submit dependency graphs
    # 如果不需要依赖关系图，可以删除这部分
    - name: Generate and submit dependency graph
      run: mvn dependency:tree  # 运行 Maven 的依赖关系任务
